modLoader="javafml"

loaderVersion="[43,)"

license="MIT"

[[mods]]

modId="tnmg"

version="0.0.1-1.20.1"

displayName="Create: The Nuclear Must Grow"

logoFile="logo.png"

authors="RedGreenBlue"

description="Nuclear Technology addon for Create and The Factory Must Grow!"

[[dependencies.tnmg]]

modId="forge"

mandatory=true

versionRange="[43,)"

ordering="NONE"

side="BOTH"

[[dependencies.tnmg]]

modId="minecraft"

mandatory=true

versionRange="[1.20.1,)"

ordering="NONE"

side="BOTH"

[[dependencies.tnmg]]

modId="create"

mandatory=true

versionRange="[0.5.1.i,)"

ordering="NONE"

side="BOTH"